{"uuid": "47bb1b27-fcbf-4557-9e81-d280f50ec9db", "children": ["ed9fc158-49aa-4b66-9a05-941ed5a5f6ff"], "befores": [{"name": "appium_driver", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ba393c0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/shaikmohamedimran/PycharmProjects/E_farm_Mobile_D2FO/Testcases/conftest.py\", line 107, in appium_driver\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", desired_cap)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 235, in __init__\n    super().__init__(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 327, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1725342827163, "stop": 1725342827164}], "start": 1725342827163, "stop": 1725342827325}